name: "web-app"
services:
  mongodb:
    image: mongo
    container_name: mongonext-database
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongonext:
    build: .
    image: mongonext-backend
    container_name: mongonext-backend
    ports:
      - "8080:8080"
    links:
        - mongodb
  mongo-express:
    image: mongo-express
    container_name: tools-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    links:
      - mongodb


