name: mongonext-backend-with-maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sam Jackson Greeter
      uses: lob/action_sam_jackson@0.0.2
      with:
        message: '<Greetings! Welcome to my Github repository. />'
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '22.0.1'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.4

    - name: Build with Maven
      run: mvn clean install

    - name: Super-Linter
      run: super-linter/super-linter@v6.7.0

