name: Build with Maven & Push image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '22.0.1'
        distribution: 'oracle'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.4

    - name: Build with Maven
      run: mvn clean install

    - name: Build & Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  
        docker image build -t ${{ secrets.DOCKER_USERNAME }}/mongonext-backend:v1 .
        docker push ${{ secrets.DOCKER_USERNAME }}/mongonext-backend:v1

